/**
 * Entropix Design Tokens Build Script
 *
 * Uses Style Dictionary v4 with W3C DTCG format to compile
 * design tokens into platform-specific outputs:
 *
 *   - dist/web/variables.css     → CSS custom properties
 *   - dist/web/tokens.js         → ES module for web (TypeScript-authored)
 *   - dist/native/tokens.js      → ES module for React Native (no px units)
 *   - dist/themes/light.css      → Light theme CSS (scoped to [data-theme="light"])
 *   - dist/themes/dark.css       → Dark theme CSS (scoped to [data-theme="dark"])
 *   - dist/native/light.js       → Light theme ES module for React Native
 *   - dist/native/dark.js        → Dark theme ES module for React Native
 */

import StyleDictionary from "style-dictionary";
import type { Config, TransformedToken } from "style-dictionary/types";

// ─── Custom Transform: Strip px for React Native ────────────────────────────
// RN uses unitless numbers for dimensions. This strips "px" and returns a number.
StyleDictionary.registerTransform({
  name: "dimension/pixelToNumber",
  type: "value",
  filter: (token: TransformedToken) => {
    return token.$type === "dimension" || token.type === "dimension";
  },
  transform: (token: TransformedToken) => {
    const value = token.$value ?? token.value;
    if (typeof value === "string" && value.endsWith("px")) {
      return parseFloat(value);
    }
    return value;
  },
});

// ─── Custom Transform: Shadow to RN format ──────────────────────────────────
// Converts DTCG shadow objects to React Native shadow properties
StyleDictionary.registerTransform({
  name: "shadow/reactNative",
  type: "value",
  filter: (token: TransformedToken) => {
    return token.$type === "shadow" || token.type === "shadow";
  },
  transform: (token: TransformedToken) => {
    const value = token.$value ?? token.value;
    if (typeof value !== "object" || value === null) return value;

    const parseNum = (v: string | number) =>
      typeof v === "string" ? parseFloat(v) : v;

    return {
      shadowOffset: {
        width: parseNum(value.offsetX ?? 0),
        height: parseNum(value.offsetY ?? 0),
      },
      shadowRadius: parseNum(value.blur ?? 0),
      shadowColor: value.color ?? "#000000",
      shadowOpacity: 1,
      elevation: Math.round(parseNum(value.blur ?? 0) / 2),
    };
  },
});

// ─── Custom Transform: Duration to number (ms) for RN ───────────────────────
StyleDictionary.registerTransform({
  name: "duration/milliseconds",
  type: "value",
  filter: (token: TransformedToken) => {
    return token.$type === "duration" || token.type === "duration";
  },
  transform: (token: TransformedToken) => {
    const value = token.$value ?? token.value;
    if (typeof value === "string" && value.endsWith("ms")) {
      return parseFloat(value);
    }
    return value;
  },
});

// ─── Custom Format: ES module with typed export ─────────────────────────────
StyleDictionary.registerFormat({
  name: "javascript/esm-tokens",
  format: ({ dictionary }) => {
    const tokens: Record<string, unknown> = {};
    dictionary.allTokens.forEach((token) => {
      const name = token.name;
      tokens[name] = token.$value ?? token.value;
    });

    return [
      "// Auto-generated by Entropix Design Tokens build",
      "// Do not edit manually",
      "",
      `export const tokens = ${JSON.stringify(tokens, null, 2)};`,
      "",
    ].join("\n");
  },
});

// ─── Base config: all tokens (primitives + semantic + components) ───────────
const baseConfig: Config = {
  source: [
    "src/primitives/**/*.json",
    "src/semantic/**/*.json",
    "src/components/**/*.json",
  ],
  usesDtcg: true,
  log: {
    verbosity: "default",
  },
  platforms: {
    web: {
      transformGroup: "css",
      buildPath: "dist/web/",
      prefix: "entropix",
      files: [
        {
          destination: "variables.css",
          format: "css/variables",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    "web-js": {
      transformGroup: "js",
      buildPath: "dist/web/",
      prefix: "entropix",
      files: [
        {
          destination: "tokens.js",
          format: "javascript/esm-tokens",
        },
      ],
    },
    native: {
      transforms: [
        "name/camel",
        "dimension/pixelToNumber",
        "shadow/reactNative",
        "duration/milliseconds",
        "color/css",
      ],
      buildPath: "dist/native/",
      prefix: "entropix",
      files: [
        {
          destination: "tokens.js",
          format: "javascript/esm-tokens",
        },
      ],
    },
  },
};

// ─── Theme config factory ───────────────────────────────────────────────────
function createThemeConfig(themeName: string): Config {
  return {
    source: [
      "src/primitives/**/*.json",
      "src/semantic/**/*.json",
      `src/themes/${themeName}.json`,
      "src/components/**/*.json",
    ],
    usesDtcg: true,
    log: {
      verbosity: "silent",
    },
    platforms: {
      // CSS output: [data-theme="light"] / [data-theme="dark"]
      [`theme-${themeName}`]: {
        transformGroup: "css",
        buildPath: "dist/themes/",
        prefix: "entropix",
        files: [
          {
            destination: `${themeName}.css`,
            format: "css/variables",
            options: {
              outputReferences: true,
              selector: `[data-theme="${themeName}"]`,
            },
          },
        ],
      },
      // Native JS output: dist/native/light.js / dist/native/dark.js
      [`theme-${themeName}-native`]: {
        transforms: [
          "name/camel",
          "dimension/pixelToNumber",
          "shadow/reactNative",
          "duration/milliseconds",
          "color/css",
        ],
        buildPath: "dist/native/",
        prefix: "entropix",
        files: [
          {
            destination: `${themeName}.js`,
            format: "javascript/esm-tokens",
          },
        ],
      },
    },
  };
}

// ─── Build ──────────────────────────────────────────────────────────────────
async function build() {
  console.log("\n🔨 Building Entropix Design Tokens...\n");

  // 1. Build base tokens (all primitives + semantic + components)
  console.log("📦 Building base tokens...");
  const baseSD = new StyleDictionary(baseConfig);
  await baseSD.buildAllPlatforms();
  console.log("   ✅ Base tokens built\n");

  // 2. Build theme-specific CSS
  const themes = ["light", "dark"];
  for (const theme of themes) {
    console.log(`🎨 Building ${theme} theme...`);
    const themeSD = new StyleDictionary(createThemeConfig(theme));
    await themeSD.buildAllPlatforms();
    console.log(`   ✅ ${theme} theme built\n`);
  }

  // 3. Generate .d.ts files for JS token outputs
  console.log("📝 Generating type declarations...");
  const { writeFileSync } = await import("fs");
  const dtsContent = `export declare const tokens: Record<string, string | number | object>;\n`;
  const dtsFiles = [
    "dist/web/tokens.d.ts",
    "dist/native/tokens.d.ts",
    "dist/native/light.d.ts",
    "dist/native/dark.d.ts",
  ];
  for (const file of dtsFiles) {
    writeFileSync(file, dtsContent, "utf-8");
  }
  console.log("   ✅ Type declarations generated\n");

  console.log("✅ All tokens built successfully!\n");
}

build().catch((err) => {
  console.error("❌ Token build failed:", err);
  process.exit(1);
});
