/**
 * Entropix Design Tokens Build Script
 *
 * Uses Style Dictionary v4 with W3C DTCG format to compile
 * design tokens into platform-specific outputs.
 *
 * Supports multi-brand token generation:
 *   - Default brand: dist/web/, dist/themes/, dist/native/
 *   - Custom brands: dist/brands/{name}/web/, dist/brands/{name}/themes/, dist/brands/{name}/native/
 */

import StyleDictionary from "style-dictionary";
import type { Config, TransformedToken } from "style-dictionary/types";
import { readdirSync, existsSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

// ─── Custom Transform: Strip px for React Native ────────────────────────────
StyleDictionary.registerTransform({
  name: "dimension/pixelToNumber",
  type: "value",
  filter: (token: TransformedToken) => {
    return token.$type === "dimension" || token.type === "dimension";
  },
  transform: (token: TransformedToken) => {
    const value = token.$value ?? token.value;
    if (typeof value === "string" && value.endsWith("px")) {
      return parseFloat(value);
    }
    return value;
  },
});

// ─── Custom Transform: Shadow to RN format ──────────────────────────────────
StyleDictionary.registerTransform({
  name: "shadow/reactNative",
  type: "value",
  filter: (token: TransformedToken) => {
    return token.$type === "shadow" || token.type === "shadow";
  },
  transform: (token: TransformedToken) => {
    const value = token.$value ?? token.value;
    if (typeof value !== "object" || value === null) return value;

    const parseNum = (v: string | number) =>
      typeof v === "string" ? parseFloat(v) : v;

    return {
      shadowOffset: {
        width: parseNum(value.offsetX ?? 0),
        height: parseNum(value.offsetY ?? 0),
      },
      shadowRadius: parseNum(value.blur ?? 0),
      shadowColor: value.color ?? "#000000",
      shadowOpacity: 1,
      elevation: Math.round(parseNum(value.blur ?? 0) / 2),
    };
  },
});

// ─── Custom Transform: Duration to number (ms) for RN ───────────────────────
StyleDictionary.registerTransform({
  name: "duration/milliseconds",
  type: "value",
  filter: (token: TransformedToken) => {
    return token.$type === "duration" || token.type === "duration";
  },
  transform: (token: TransformedToken) => {
    const value = token.$value ?? token.value;
    if (typeof value === "string" && value.endsWith("ms")) {
      return parseFloat(value);
    }
    return value;
  },
});

// ─── Custom Format: ES module with typed export ─────────────────────────────
StyleDictionary.registerFormat({
  name: "javascript/esm-tokens",
  format: ({ dictionary }) => {
    const tokens: Record<string, unknown> = {};
    dictionary.allTokens.forEach((token) => {
      const name = token.name;
      tokens[name] = token.$value ?? token.value;
    });

    return [
      "// Auto-generated by Entropix Design Tokens build",
      "// Do not edit manually",
      "",
      `export const tokens = ${JSON.stringify(tokens, null, 2)};`,
      "",
    ].join("\n");
  },
});

// ─── Brand Discovery ────────────────────────────────────────────────────────
function discoverBrands(): string[] {
  const brandsDir = join(process.cwd(), "src/brands");
  if (!existsSync(brandsDir)) return [];

  return readdirSync(brandsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
}

// ─── Native transforms (shared) ────────────────────────────────────────────
const nativeTransforms = [
  "name/camel",
  "dimension/pixelToNumber",
  "shadow/reactNative",
  "duration/milliseconds",
  "color/css",
];

// ─── Brand Base Config Factory ──────────────────────────────────────────────
function createBrandBaseConfig(brand: string): Config {
  const isDefault = brand === "default";
  const brandDir = `src/brands/${brand}`;

  const source = [
    "src/primitives/**/*.json",
    ...(isDefault ? [] : existsSync(join(process.cwd(), brandDir, "primitives"))
      ? [`${brandDir}/primitives/**/*.json`] : []),
    "src/semantic/**/*.json",
    ...(isDefault ? [] : existsSync(join(process.cwd(), brandDir, "semantic"))
      ? [`${brandDir}/semantic/**/*.json`] : []),
    "src/components/**/*.json",
  ];

  const buildPathWeb = isDefault ? "dist/web/" : `dist/brands/${brand}/web/`;
  const buildPathNative = isDefault ? "dist/native/" : `dist/brands/${brand}/native/`;
  const cssSelector = isDefault ? ":root" : `[data-brand="${brand}"]`;

  return {
    source,
    usesDtcg: true,
    log: { verbosity: isDefault ? "default" : "silent" },
    platforms: {
      web: {
        transformGroup: "css",
        buildPath: buildPathWeb,
        prefix: "entropix",
        files: [
          {
            destination: "variables.css",
            format: "css/variables",
            options: { outputReferences: true, selector: cssSelector },
          },
        ],
      },
      "web-js": {
        transformGroup: "js",
        buildPath: buildPathWeb,
        prefix: "entropix",
        files: [
          { destination: "tokens.js", format: "javascript/esm-tokens" },
        ],
      },
      native: {
        transforms: nativeTransforms,
        buildPath: buildPathNative,
        prefix: "entropix",
        files: [
          { destination: "tokens.js", format: "javascript/esm-tokens" },
        ],
      },
    },
  };
}

// ─── Brand Theme Config Factory ─────────────────────────────────────────────
function createBrandThemeConfig(brand: string, theme: string): Config {
  const isDefault = brand === "default";
  const brandDir = `src/brands/${brand}`;
  const brandThemeFile = `${brandDir}/themes/${theme}.json`;
  const hasBrandTheme = !isDefault && existsSync(join(process.cwd(), brandThemeFile));

  const source = [
    "src/primitives/**/*.json",
    ...(isDefault ? [] : existsSync(join(process.cwd(), brandDir, "primitives"))
      ? [`${brandDir}/primitives/**/*.json`] : []),
    "src/semantic/**/*.json",
    ...(isDefault ? [] : existsSync(join(process.cwd(), brandDir, "semantic"))
      ? [`${brandDir}/semantic/**/*.json`] : []),
    `src/themes/${theme}.json`,
    ...(hasBrandTheme ? [brandThemeFile] : []),
    "src/components/**/*.json",
  ];

  const buildPathThemes = isDefault ? "dist/themes/" : `dist/brands/${brand}/themes/`;
  const buildPathNative = isDefault ? "dist/native/" : `dist/brands/${brand}/native/`;

  const cssSelector = isDefault
    ? `[data-theme="${theme}"]`
    : `[data-brand="${brand}"][data-theme="${theme}"]`;

  return {
    source,
    usesDtcg: true,
    log: { verbosity: "silent" },
    platforms: {
      [`theme-${theme}`]: {
        transformGroup: "css",
        buildPath: buildPathThemes,
        prefix: "entropix",
        files: [
          {
            destination: `${theme}.css`,
            format: "css/variables",
            options: { outputReferences: true, selector: cssSelector },
          },
        ],
      },
      [`theme-${theme}-native`]: {
        transforms: nativeTransforms,
        buildPath: buildPathNative,
        prefix: "entropix",
        files: [
          { destination: `${theme}.js`, format: "javascript/esm-tokens" },
        ],
      },
    },
  };
}

// ─── Generate .d.ts files ───────────────────────────────────────────────────
function generateDTS(brand: string) {
  const dtsContent = `export declare const tokens: Record<string, string | number | object>;\n`;
  const isDefault = brand === "default";
  const base = isDefault ? "dist" : `dist/brands/${brand}`;

  const files = [
    `${base}/${isDefault ? "web" : "web"}/tokens.d.ts`,
    `${base}/${isDefault ? "native" : "native"}/tokens.d.ts`,
    `${base}/${isDefault ? "native" : "native"}/light.d.ts`,
    `${base}/${isDefault ? "native" : "native"}/dark.d.ts`,
  ];

  for (const file of files) {
    const dir = file.substring(0, file.lastIndexOf("/"));
    mkdirSync(dir, { recursive: true });
    writeFileSync(file, dtsContent, "utf-8");
  }
}

// ─── Build ──────────────────────────────────────────────────────────────────
async function build() {
  console.log("\n🔨 Building Entropix Design Tokens...\n");

  const themes = ["light", "dark"];
  const customBrands = discoverBrands();
  const allBrands = ["default", ...customBrands];

  console.log(`📋 Brands: ${allBrands.join(", ")}`);
  console.log(`🎨 Themes: ${themes.join(", ")}\n`);

  for (const brand of allBrands) {
    const label = brand === "default" ? "default" : `brand: ${brand}`;

    // Build base tokens
    console.log(`📦 Building base tokens (${label})...`);
    const baseSD = new StyleDictionary(createBrandBaseConfig(brand));
    await baseSD.buildAllPlatforms();
    console.log(`   ✅ Base tokens built\n`);

    // Build theme-specific outputs
    for (const theme of themes) {
      console.log(`🎨 Building ${theme} theme (${label})...`);
      const themeSD = new StyleDictionary(createBrandThemeConfig(brand, theme));
      await themeSD.buildAllPlatforms();
      console.log(`   ✅ ${theme} theme built\n`);
    }

    // Generate .d.ts files
    generateDTS(brand);
  }

  console.log("📝 Type declarations generated");
  console.log("\n✅ All tokens built successfully!\n");
  console.log(`   Brands: ${allBrands.length} (${allBrands.join(", ")})`);
  console.log(`   Outputs per brand: base + ${themes.length} themes`);
  console.log(`   Total builds: ${allBrands.length * (1 + themes.length)}\n`);
}

build().catch((err) => {
  console.error("❌ Token build failed:", err);
  process.exit(1);
});
